# fly.toml app configuration file generated for botrading on 2025-02-27T18:43:04-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'botrading'
primary_region = 'gru'

[build]
  builder = 'paketobuildpacks/builder:base'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
