[build]
  builtin = "python"
  python_version = "3.10"
[deploy]
  release_command = "uvicorn main:app --host 0.0.0.0 --port 8080"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
