# fly.toml app configuration file generated for trading-autobot on 2025-02-25T10:48:08-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

aapp = "tradingbo"
primary_region = "gru"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_080
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "2gb"